### PR TITLE
DEV-274: Add Footer for cat match

### PR DESCRIPTION
**Pull request by SulthanNK**
- **Ticket No**: DEV-274

- **Work**: 
  - Refactored the code due to my prettier extension (Sorry, Thats why it shows alot changes).
  - Added footer with copyrights and linking to our main site.

- **Reference**:

   image

### CODE REVIEW

**Review by DeniceLayton — CHANGES_REQUESTED** [review]
Hey Sulthan, thanks for doing this its looking great. However could i ask for some small changes?

1. Could you change the link name from JDG to junior developer Group please? This is totally my fault and should have said so on the Jira ticket. We are called "Junior Developer Group" and it just doesn't make sense to have  it as JDG.

2. Could you please make a change so that the link is obviously a link. By that i mean either  the text is a different colour, or  if you move over it the colour changes or the text gets  slightly bigger , something so it is very obvious its a link.  We want people to know about us and want to click it. I'm happy for you to explore that and see what looks best. Also please make sure you include :visited  and :active  selectors in CSS  so that it will indicate when a link has been clicked. if we don't set this as something nice then we just get  the default purple colours , so its an opportunity to set something better here or align with the projects colour scheme etc.

thanks for making these changes, any questions or help please give me a shout.

**Comment by SulthanNK** [comment]
Hey @Denice-S , 

- Changed the link title from "JDG" to "Junior Developer Group" as you mentioned in comment.
- Added some styles that changes the color of text and bottom side border with small animation while hovering and clicking it.

**Comment by DeniceLayton** [comment]
hi @SulthanNK ,

Thanks for making those changes on the ticket for the cat match footer, it looks so much better they are great I love the underline it looks fab!

I am however a bit confused as i have looked at the code and some of the CSS isn't being applied. For example when i open this and view it, "Junior Developer Group" is in dark green and its underline is green ( when you click it goes light green for a second) 

BUT you have styles that are applying a purple and a light purple which are being overridden by the green styles that are in the ::visited bit.

i just wanted to check with you before merging what you were intending this to look like ( i.e is it supposed to be all green or were you intending a purple underline for example) ... just incase you needed to make a change?

please let me know before i merge, and feel free to  buzz me on discord if its easier (@cendei)

**Comment by SulthanNK** [comment]
Hey @Denice-S ,

I tried the :active and :visited selectors and oops, I think some of them starts behave differently from what I thought.

My idea was initially the link and underline is purple. while we clicking it, it turns light green at the moment, and after site opened(means we visited the link, so both link and underline turns into dark green). 

Now, need to figure out where I messed up those things.

**Comment by mateahoward** [comment]
Hiya @SulthanNK, just checking in 😄 We seem to have conflicts with this branch, would you be okay looking at that yourself or would you prefer some help? Let me know 😄

**Comment by SulthanNK** [comment]
Kindly, help me to solve this @mateahoward 😅. It's a first time for me

**Comment by mateahoward** [comment]
Hey @SulthanNK, I'll be taking these conflicts to our live coding session tonight :)

**Comment by mateahoward** [comment]
Hello @SulthanNK and @Denice-S 👋 I've pushed in the conflict fixes but I'll just need you both to check if it's all good (I've checked against what we have published on main but it was a lot and I just wanna make sure we didn't lose anything) ❤️

**Review by SulthanNK — COMMENTED** [review]
LGTM!

**Comment by SulthanNK** [comment]
Hello @mateahoward, I pull the changes to my local and checked it. It seems everything looks fine based on what we did earlier. Hope check once with the admin team before merge.

**Comment by DeniceLayton** [comment]
hey @SulthanNK  and @mateahoward  this looks like it has been resolved , i've had a look and it looks all good to me i don't think we lost anything. 

Sulthan - did you want to have a look why your CSS i sent working correctly as you wanted it to ? - The link is still green with a green underline,  and you had said -  __"My_ idea was initially the link and underline is purple. while we clicking it, it turns light _green_ at the moment, and after site opened(means we visited the link, so both link and underline turns into dark green)."_ 

Do you want to take a look before i merge it in.? We can always leave it as green that looks perfectly fine to me - but it might be useful to know why things aren't working as you intended them to? If your not sure whats happening and need some help or you want us to take a look then let me know.

**Comment by SulthanNK** [comment]
Hey @Denice-S, If possible just have a look. I tried and don't know where I missing. So, If you have look and mention it will be helpful also for me to learn from those mistakes again.

**Comment by mateahoward** [comment]
> Hey @Denice-S, If possible just have a look. I tried and don't know where I missing. So, If you have look and mention it will be helpful also for me to learn from those mistakes again.

Hey hey 😄 I think you've done it good sir:

**If it hasn't been clicked on** -> colour is purple 
(you can also open this project in incognito and then it will behave like you've never seen it before, making the text purple)

**If it has been clicked on/visited** -> colour is green 

I might be missing something here but it looks good/like you've intended it to look? 

You can see those changes in chrome inspector if you click on ':hov' button on the right-hand side:

image

If I'm missing the point pls let me know and I'll be more than happy to help out 😄

**Comment by DeniceLayton** [comment]
Hey @SulthanNK , Matea and myself have had a look... it turns out what you have done is absolutely fine and 100% spot on no problems, great work!. So i am merging this in.

So why was i seeing it as always green ? -  Well this was due to a cache issue  on my browser -so i was always seeing the visited link which was green. 

Totally my bad !  and very frustrating as this is something i often forget about  and has led me on a wild goose chase before.  So in terms of you code there is nothing for you to learn here you have done great .. and i have to remember to clear the cache if it doesn't look quite right just to be sure!

**Review by DeniceLayton — APPROVED** [review]

**Pull request merged**
