### PR TITLE
form sections changed to fieldset

### PR DESCRIPTION
**Pull request by Jaytru1997**

### CODE REVIEW

**Review by DeniceLayton — CHANGES_REQUESTED** [review]
Hi Jay,  Thanks for having a look at this ticket,  i've just had a look at the hero section, (im using chrome with the zoom on 100%) , and i think a couple of changes are needed.
1. The image seems far too big could you reduce it down a bit please?
2. Could you increase the size of the heading 
3. Could you increase the size of the button ?

I think this will help it look more balanced , and make sure the button stands out more , as the image is over dominating the page  at the moment - but have a play and see what  you think works best.

**Review by DeniceLayton — CHANGES_REQUESTED** [review]
Jay,  Thanks for this, 
I  am no expert on the html fieldset tag , but having had a quick look myself i am wondering if we should change the h4's to be the legend tag  as fieldsets need a legend? as these are the sections titles anyway and we can style the legend tag then?

**Comment by Jaytru1997** [comment]
I made the changes and made it mobile responsive as well

**Comment by DeniceLayton** [comment]
Jay is going to do a seperate  branch and pull request per ticket he has so closing this one

**Pull request closed without merging**
