### PR TITLE
DEV-179 Clear Search Form

### PR DESCRIPTION
**Pull request by Kyle-Atienza**

### CODE REVIEW

**Review by DeniceLayton — CHANGES_REQUESTED** [review]
Hi Kyle,

This is great work on this ticket, you are right this will eventually be linked up to a button so when the user clicks it - they can reset the form and search again - the form isn't completed yet though so we don't have one yet!. 

Also because i merged your other pull request - this branch now has conflicts. 

I dont know how familiar you are with git - are you happy resolving these conflicts yourself?( it would involve pulling down from the main branch again and then merging those changes into this one (DEV-179 Clear Search Form) and then pushing again.

feel free to shout out if you need any assistance

**Comment by DeniceLayton** [comment]
Hi Kyle, Thanks for taking care of the merge issues  so quickly.....however, you have also made a change to a piece of code that wasn't in your work /ticket ....
so you have changed line 62 from : _formValues[input.id] = parseInt(input.value)_; to _formValues[input.id] = input.value_;

I'm not sure why you needed to change this ..but your logic is not working now. I cannot see the console log of the catResults you have  on line 41 whereas i could in your work i merged yesterday .

Could you please check , and reverse the change to this line of code and push again

Thanks

Denice

**Comment by Kyle-Atienza** [comment]
ahh I think i have confused when I resolved some conflicts, will get back to it

**Review by DeniceLayton — APPROVED** [review]
The conflicts are now resolved merging in

**Pull request merged**
